service: aws-serverless-task-api

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'ap-south-1'}
  stage: ${opt:stage, env:STAGE, 'dev'}
  memorySize: 512
  timeout: 10
  environment:
    TASKS_TABLE: ${env:TASKS_TABLE, self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.tableName}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  tableName: ${self:service}-${self:provider.stage}-tasks
  dotenv:
    include:
      - STAGE
      - TASKS_TABLE
      - NODE_ENV

functions:
  health:
    handler: src/health.health
    events:
      - http:
          path: /health
          method: get
          cors: true

  listTasks:
    handler: src/tasks.listTasks
    events:
      - http:
          path: /tasks
          method: get
          cors: true

  createTask:
    handler: src/tasks.createTask
    events:
      - http:
          path: /tasks
          method: post
          cors: true

  getTask:
    handler: src/tasks.getTask
    events:
      - http:
          path: /tasks/{id}
          method: get
          cors: true

  updateTask:
    handler: src/tasks.updateTask
    events:
      - http:
          path: /tasks/{id}
          method: put
          cors: true

  deleteTask:
    handler: src/tasks.deleteTask
    events:
      - http:
          path: /tasks/{id}
          method: delete
          cors: true

resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        SSESpecification:
          SSEEnabled: true
